apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: jenkins
    fsType: ext4
    
    
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  
spec:
  storageClassName: ""
  volumeName: jenkins
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
